name: Manually Trigger Kernel Build (COPR)

on:
  workflow_dispatch:

jobs:
  trigger-copr-build:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Install copr-cli package
        run: dnf install -y copr-cli

      - name: Trigger COPR Build
        run: |
          mkdir ~/.config
          tee ~/.config/copr > /dev/null <<EOF
          [copr-cli]
          login = ${{ secrets.COPR_LOGIN }}
          username = vncvltvred
          token = ${{ secrets.COPR_TOKEN }}
          copr_url = https://copr.fedorainfracloud.org
          EOF

          copr-cli buildscm --clone-url https://github.com/dangbroitsdon/copr-kernel-cachyos-server --subdir . --spec kernel-cachyos-server.spec --timeout 72000 --nowait vncvltvred/kernel-cachyos-server
